/* MERIDIAN: автономный прототип. Данные и события синхронизируются между вкладками одного браузера. */
const KEY='meridian-download-v2', CART='meridian-download-cart-v2';
// Hash navigation allows opening this export directly from disk.
const uid=()=>typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
const transient={};let storageUnavailable=false;
function getLocal(k){try{return localStorage.getItem(k)}catch{storageUnavailable=true;return transient[k]||null}}
function setLocal(k,v){try{localStorage.setItem(k,v)}catch(e){if(e.name==='QuotaExceededError')throw e;storageUnavailable=true;transient[k]=v}}
function getSession(k){try{return sessionStorage.getItem(k)}catch{return transient[k]||null}}
function setSession(k,v){try{sessionStorage.setItem(k,v)}catch{transient[k]=String(v)}}
const seed={categories:[{id:'main',name:'Основные блюда'},{id:'salad',name:'Салаты'},{id:'soup',name:'Супы'}],dishes:[
{id:'salmon',name:'Лосось с зелёным салатом',line1:'Нежный лосось',line2:'И ЗЕЛЁНЫЙ САЛАТ',category:'main',price:24,weight:320,time:20,image:'assets/salmon.png',description:'Обжаренный до золотистой корочки лосось, хрустящая зелень и лёгкая цитрусовая заправка. Простые ингредиенты. Идеальный баланс.',ingredients:'Филе лосося, микс салатов, огурец, авокадо, лимон, оливковое масло.',allergens:'Рыба',available:true},
{id:'steak',name:'Стейк с молодым картофелем',line1:'Сочный стейк',line2:'И МОЛОДОЙ КАРТОФЕЛЬ',category:'main',price:32,weight:420,time:25,image:'assets/steak.png',description:'Стейк на гриле с румяным молодым картофелем, ароматным розмарином и насыщенным перечным соусом.',ingredients:'Говядина, картофель, розмарин, сливочное масло, чёрный перец.',allergens:'Молоко',available:true},
{id:'pumpkin',name:'Тыквенный крем-суп',line1:'Печёная тыква',line2:'И НЕЖНЫЕ СЛИВКИ',category:'soup',price:12,weight:300,time:12,image:'assets/soup.png',description:'Бархатистый суп из запечённой тыквы со сливками, тыквенными семечками и свежей зеленью.',ingredients:'Тыква, сливки, овощной бульон, тыквенные семечки, зелень.',allergens:'Молоко',available:true},
{id:'salad',name:'Салат с лососем',line1:'Свежая зелень',line2:'И ТЁПЛЫЙ ЛОСОСЬ',category:'salad',price:18,weight:240,time:15,image:'assets/salmon.png',description:'Лёгкий салат с тёплым лососем, свежими овощами и лимонной заправкой.',ingredients:'Лосось, салат, огурец, авокадо, лимон.',allergens:'Рыба',available:true}],orders:[]};
const clone=o=>JSON.parse(JSON.stringify(o));
function read(k,fallback){try{return JSON.parse(getLocal(k))||clone(fallback)}catch{return clone(fallback)}}
let db=read(KEY,seed),cart=read(CART,{}),table=Number(getSession('meridian-table'))||1,category='all',selected='salmon',filter='active';
const params=new URLSearchParams(location.search);if(params.has('table')){const n=Number(params.get('table'));if(Number.isInteger(n)&&n>0&&n<=50){table=n;setSession('meridian-table',table)}}
const app=document.getElementById('app'),editor=document.getElementById('editor');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const statusNames={new:'Новый',cooking:'Готовится',ready:'Готов',served:'Подан',cancelled:'Отменён'};
const route=()=>{try{return decodeURIComponent(location.hash.slice(1)||'/').split('?')[0].replace(/\/$/,'')||'/'}catch{return '/404'}};
function save(){try{setLocal(KEY,JSON.stringify(db));return true}catch{toast('Не удалось сохранить: память браузера заполнена');return false}}
function saveCart(){try{setLocal(CART,JSON.stringify(cart))}catch{toast('Не удалось сохранить корзину')}}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}
function go(path){if(location.hash==='#'+path)render();else location.hash=path;window.scrollTo(0,0)}
const count=()=>Object.values(cart).reduce((a,b)=>a+b,0);
const dish=id=>db.dishes.find(d=>d.id===id);
const cartItems=()=>Object.entries(cart).map(([id,qty])=>({d:dish(id),qty})).filter(x=>x.d);
const subtotal=()=>cartItems().reduce((s,{d,qty})=>s+d.price*qty,0);
function tableOptions(){return Array.from({length:50},(_,i)=>`<option value="${i+1}" ${table===i+1?'selected':''}>Стол ${String(i+1).padStart(2,'0')}</option>`).join('')}
function header(){const r=route();return `<header><a class="brand" href="#/" aria-label="Меридиан, меню"><span class="mark">M</span><span>MERIDIAN<small>RESTAURANT & BAR</small></span></a><nav aria-label="Основная навигация"><a class="${r==='/'?'active':''}" href="#/">Меню</a><a class="${r==='/orders'?'active':''}" href="#/orders">Мои заказы</a><a class="pill cart-link" href="#/cart"><span class="cart-label">Корзина</span><span aria-hidden="true">▢</span><span class="count">${count()}</span></a><button class="icon-btn mobile-menu" data-action="drawer" aria-label="Открыть меню">☰</button></nav></header>`}
const footer=()=>`<footer><span>© MERIDIAN · 2026</span><div><a href="#/kitchen">Кухня</a><a href="#/admin">Управление</a></div></footer>`;
function add(id,qty=1){const d=dish(id);if(!d||!d.available)throw new Error('Блюдо недоступно');if(!Number.isInteger(qty)||qty<1||qty>99)throw new Error('Количество от 1 до 99');cart[id]=Math.min(99,(cart[id]||0)+qty);saveCart();render();toast('Добавлено в корзину');return {id,quantity:cart[id]}}
function stepper(id,qty){return `<div class="stepper"><button data-action="minus" data-id="${esc(id)}" aria-label="Уменьшить количество">−</button><span>${qty}</span><button data-action="plus" data-id="${esc(id)}" aria-label="Увеличить количество" ${qty>=99?'disabled':''}>+</button></div>`}
function purchase(d,detail=false){return `<div class="purchase"><span class="price">${money(d.price)} <small>/ порция</small></span><button class="btn" data-action="add" data-id="${esc(d.id)}">В корзину <span>＋</span></button></div>${!detail?`<a class="back" style="margin:20px 0 0" href="#/dish/${encodeURIComponent(d.id)}">Подробнее о блюде ↗</a>`:''}`}
function dishHero(d,detail=false){return `<section class="hero"><div class="plate-wrap"><img class="plate" src="${esc(d.image.replace(/^\/assets\//,'assets/'))}" alt="${esc(d.name)}"></div><div class="dish-copy"><span class="eyebrow">${esc(db.categories.find(c=>c.id===d.category)?.name||'Меню')} · MERIDIAN</span><h1>${esc(d.line1||d.name)}<strong>${esc(d.line2||'')}</strong></h1><p class="description">${esc(d.description)}</p><div class="meta"><span>${d.weight} г</span><span>◷ ${d.time} минут</span><span>Свежие ингредиенты</span></div>${purchase(d,detail)}${detail?`<div class="ingredients"><b>Состав</b><br>${esc(d.ingredients)}<br><span class="sub">Аллергены: ${esc(d.allergens||'не указаны')}</span></div>`:''}</div>${!detail?`<aside class="chef-note"><span class="tag">Выбор шефа</span><b>Сделано<br>со вкусом.</b><p>Сезонные продукты.<br>Внимание к деталям.<br>Любовь к своему делу.</p><span>Кухня MERIDIAN</span></aside>`:''}</section>`}
function menu(){const list=db.dishes.filter(d=>d.available&&(category==='all'||d.category===category));if(!list.some(d=>d.id===selected))selected=list[0]?.id;const d=dish(selected);return `<main class="shell"><div class="topline"><span class="eyebrow">Хороший день начинается со вкуса</span><select class="table-picker" data-change="table" aria-label="Ваш стол">${tableOptions()}</select></div>${d?dishHero(d):'<div class="empty"><h1>Скоро здесь появятся блюда</h1><p>Выберите другую категорию.</p></div>'}<section class="switcher" aria-label="Выбор блюда"><button class="icon-btn" data-action="prev" aria-label="Предыдущее блюдо">←</button><div class="dish-thumbs">${list.map(x=>`<button class="thumb ${x.id===selected?'active':''}" data-action="select" data-id="${esc(x.id)}"><img src="${esc(x.image.replace(/^\/assets\//,'assets/'))}" alt=""><b>${esc(x.name)}</b><span>${money(x.price)}</span></button>`).join('')}</div><button class="icon-btn" data-action="next" aria-label="Следующее блюдо">→</button></section><div class="bottomline"><div class="categories">${[{id:'all',name:'Всё меню'},...db.categories].map(c=>`<button class="${category===c.id?'active':''}" data-action="category" data-id="${esc(c.id)}">${esc(c.name)}</button>`).join('')}</div><p>Выбирайте. Пробуйте. Наслаждайтесь.</p></div></main>`}
function detail(id){const d=dish(id);if(!d||!d.available)return notFound();return `<main class="shell detail"><a class="back" href="#/">← Вернуться в меню</a>${dishHero(d,true)}</main>`}
function cartPage(){const items=cartItems();return `<main class="page"><div class="page-heading"><div><span class="eyebrow">Ваш выбор</span><h1>Корзина</h1></div><a class="pill" href="#/">＋ Добавить блюда</a></div>${!items.length?'<div class="empty"><div class="big">∅</div><h2>Вкусное ещё впереди</h2><p>Выберите первое блюдо в нашем меню.</p><a class="btn" href="#/">Открыть меню</a></div>':`<div class="cart-layout"><section>${items.map(({d,qty})=>`<div class="cart-row"><img src="${esc(d.image.replace(/^\/assets\//,'assets/'))}" alt="${esc(d.name)}"><div><a href="#/dish/${esc(d.id)}"><h3>${esc(d.name)}</h3></a><span class="sub">${d.weight} г · ${money(d.price)}${!d.available?' · Недоступно':''}</span><div class="cart-actions">${stepper(d.id,qty)}<button class="link-btn" data-action="remove" data-id="${esc(d.id)}">Убрать</button></div></div><b>${money(d.price*qty)}</b></div>`).join('')}</section><form class="summary" id="checkout"><h2>Ваш заказ</h2><p class="sub">${count()} поз. · Оплата в ресторане</p><label for="table">Номер стола</label><select id="table" name="table" required>${tableOptions()}</select><label for="note">Пожелания к заказу</label><textarea id="note" name="note" maxlength="400" placeholder="Например, соус отдельно"></textarea><div class="total"><span>Итого</span><span>${money(subtotal())}</span></div><button class="btn" type="submit">Отправить на кухню →</button><p class="sub">Проверьте номер стола перед отправкой.</p></form></div>`}</main>`}
function orderCard(o,staff=false){const next={new:['cooking','Начать готовить'],cooking:['ready','Заказ готов'],ready:['served','Заказ подан']}[o.status];return `<article class="order"><div class="order-top"><span class="eyebrow">№ ${esc(o.number)}</span><span class="status ${o.status}">${statusNames[o.status]}</span></div><h3>Стол ${String(o.table).padStart(2,'0')}</h3><span class="sub">${new Date(o.created).toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</span><ul>${o.items.map(i=>`<li><span>${esc(i.name)}</span><b>× ${i.qty}</b></li>`).join('')}</ul>${o.note?`<p class="order-note">${esc(o.note)}</p>`:''}<div class="order-bottom"><span>${o.items.reduce((s,i)=>s+i.qty,0)} поз.</span><span>${money(o.total)}</span></div>${staff&&next?`<button class="btn" data-action="status" data-id="${o.id}" data-status="${next[0]}">${next[1]} →</button>`:''}${staff&&['new','cooking'].includes(o.status)?`<button class="link-btn" style="margin-top:14px" data-action="cancel" data-id="${o.id}">Отменить заказ</button>`:''}</article>`}
function ordersPage(id){let orders=db.orders.filter(o=>o.table===table).sort((a,b)=>b.created-a.created);if(id){orders=db.orders.filter(o=>o.id===id);if(!orders.length)return notFound()}return `<main class="page"><div class="page-heading"><div><span class="eyebrow">MERIDIAN</span><h1>${id?'Заказ принят':'Мои заказы'}</h1><p class="sub">${id?'Спасибо! Статус обновится, когда кухня начнёт готовить.':'Заказы вашего стола и их готовность.'}</p></div><select class="table-picker" data-change="table" aria-label="Ваш стол">${tableOptions()}</select></div>${orders.length?`<div class="orders ${id?'order-detail':''}">${orders.map(o=>orderCard(o)).join('')}</div>`:'<div class="empty"><h2>Пока нет заказов</h2><p>Выберите блюда, и мы начнём готовить.</p></div>'}<a class="btn light" style="margin-top:25px" href="#/">Вернуться в меню</a></main>`}
function adminNav(r){return `<div class="toolbar"><a class="${r==='/admin'?'active':''}" href="#/admin">Заказы</a><a class="${r==='/admin/menu'?'active':''}" href="#/admin/menu">Блюда</a><a class="${r==='/admin/categories'?'active':''}" href="#/admin/categories">Категории</a><a href="#/kitchen">Экран кухни ↗</a></div>`}
function staffPage(kitchen=false){const r=route();const active=db.orders.filter(o=>!['served','cancelled'].includes(o.status));const list=db.orders.filter(o=>filter==='all'||(filter==='active'?!['served','cancelled'].includes(o.status):o.status===filter)).sort((a,b)=>kitchen?a.created-b.created:b.created-a.created);return `<main class="page"><div class="page-heading"><div><span class="eyebrow">MERIDIAN · ${kitchen?'KITCHEN':'CONTROL ROOM'}</span><h1>${kitchen?'На кухне':'Управление рестораном'}</h1></div><a class="pill" href="#${kitchen?'/admin':'/'}">${kitchen?'Управление':'Открыть меню'} ↗</a></div>${!kitchen?adminNav(r):''}<div class="notice">Демо на этом устройстве: меню и заказы сохраняются в браузере. Откройте меню и кухню в соседних вкладках для проверки. Доступ к управлению пока без пароля.</div><div class="stats"><div class="stat"><span>Активные заказы</span><b>${active.length}</b></div><div class="stat"><span>Занятые столы</span><b>${new Set(active.map(o=>o.table)).size}</b></div><div class="stat"><span>${kitchen?'Готовы к подаче':'Сумма заказов'}</span><b>${kitchen?db.orders.filter(o=>o.status==='ready').length:money(db.orders.filter(o=>o.status!=='cancelled').reduce((s,o)=>s+o.total,0))}</b></div></div><div class="toolbar">${[['active','Активные'],['new','Новые'],['cooking','Готовятся'],['ready','Готовы'],['all','Все заказы']].map(([id,name])=>`<button class="${filter===id?'active':''}" data-action="filter" data-id="${id}">${name}</button>`).join('')}</div>${list.length?`<section class="orders">${list.map(o=>orderCard(o,true)).join('')}</section>`:'<div class="empty"><h2>Всё спокойно</h2><p>Здесь появятся заказы гостей.</p><a class="btn light" href="#/">Сделать пробный заказ</a></div>'}</main>`}
function adminMenu(){return `<main class="page"><div class="page-heading"><div><span class="eyebrow">MERIDIAN · CONTROL ROOM</span><h1>Меню ресторана</h1></div><button class="btn" data-action="edit-dish">＋ Добавить блюдо</button></div>${adminNav('/admin/menu')}<div class="table-wrap"><table><thead><tr><th>БЛЮДО</th><th>КАТЕГОРИЯ</th><th>ЦЕНА</th><th>В МЕНЮ</th><th>ДЕЙСТВИЯ</th></tr></thead><tbody>${db.dishes.map(d=>`<tr><td><img src="${esc(d.image.replace(/^\/assets\//,'assets/'))}" alt="">${esc(d.name)}</td><td>${esc(db.categories.find(c=>c.id===d.category)?.name||'—')}</td><td>${money(d.price)}</td><td><input type="checkbox" ${d.available?'checked':''} data-change="available" data-id="${esc(d.id)}" aria-label="Доступность: ${esc(d.name)}"></td><td><button class="edit-btn" data-action="edit-dish" data-id="${esc(d.id)}">Изменить</button> <button class="edit-btn" data-action="delete-dish" data-id="${esc(d.id)}">Удалить</button></td></tr>`).join('')}</tbody></table></div></main>`}
function adminCategories(){return `<main class="page"><div class="page-heading"><div><span class="eyebrow">MERIDIAN · CONTROL ROOM</span><h1>Категории</h1></div><button class="btn" data-action="edit-category">＋ Добавить категорию</button></div>${adminNav('/admin/categories')}${db.categories.map(c=>`<div class="category-row"><span><b>${esc(c.name)}</b><br><small class="sub">Блюд: ${db.dishes.filter(d=>d.category===c.id).length}</small></span><div><button class="edit-btn" data-action="edit-category" data-id="${esc(c.id)}">Изменить</button> <button class="edit-btn" data-action="delete-category" data-id="${esc(c.id)}">Удалить</button></div></div>`).join('')}${!db.categories.length?'<p class="sub">Добавьте первую категорию.</p>':''}</main>`}
function notFound(){return `<main class="page empty"><div class="big">404</div><h1>Такого блюда нет в меню</h1><p>Кажется, вы свернули не к тому столику.<br>Вернёмся туда, где вкусно?</p><a class="btn" href="#/">Вернуться в меню →</a></main>`}
function render(){const r=route();let content;if(r==='/')content=menu();else if(r.startsWith('/dish/'))content=detail(r.slice(6));else if(r==='/cart')content=cartPage();else if(r==='/orders')content=ordersPage();else if(r.startsWith('/order/'))content=ordersPage(r.slice(7));else if(r==='/kitchen')content=staffPage(true);else if(r==='/admin')content=staffPage();else if(r==='/admin/menu')content=adminMenu();else if(r==='/admin/categories')content=adminCategories();else content=notFound();app.innerHTML=header()+content+footer();document.title=(r==='/kitchen'?'Кухня':r.startsWith('/admin')?'Управление':r==='/cart'?'Корзина':'Меню')+' · MERIDIAN'}
function openEditor(html){editor.innerHTML=html;editor.showModal()}
function editDish(id){const d=dish(id)||{name:'',line1:'',line2:'',category:db.categories[0]?.id,price:0,weight:250,time:15,image:'assets/salmon.png',description:'',ingredients:'',allergens:'',available:true};if(!db.categories.length){toast('Сначала добавьте категорию');return}openEditor(`<h2>${id?'Редактировать':'Новое'} блюдо</h2><form id="dish-form" data-id="${esc(id||'')}"><label>Название<input name="name" value="${esc(d.name)}" required maxlength="80"></label><div class="row"><label>Первая строка заголовка<input name="line1" value="${esc(d.line1)}" maxlength="45"></label><label>Вторая строка<input name="line2" value="${esc(d.line2)}" maxlength="45"></label></div><div class="row"><label>Категория<select name="category">${db.categories.map(c=>`<option value="${esc(c.id)}" ${c.id===d.category?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Цена, $<input type="number" name="price" min="0.01" max="9999" step="0.01" value="${d.price}" required></label></div><div class="row"><label>Вес, г<input type="number" name="weight" min="1" max="10000" value="${d.weight}" required></label><label>Время, мин<input type="number" name="time" min="1" max="240" value="${d.time}" required></label></div><label>Описание<textarea name="description" maxlength="700" required>${esc(d.description)}</textarea></label><label>Состав<input name="ingredients" value="${esc(d.ingredients)}" maxlength="400"></label><label>Аллергены<input name="allergens" value="${esc(d.allergens)}" maxlength="150"></label><label>Фото<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"><small class="sub">До 3 МБ. Текущее фото сохранится, если не выбрать новое.</small></label><label><span><input name="available" type="checkbox" ${d.available?'checked':''}> Доступно для заказа</span></label><div class="modal-actions"><button type="button" class="btn light" data-action="close">Отмена</button><button class="btn" type="submit">Сохранить</button></div></form>`)}
function editCategory(id){const c=db.categories.find(c=>c.id===id);openEditor(`<h2>${id?'Изменить':'Добавить'} категорию</h2><form id="category-form" data-id="${esc(id||'')}"><label>Название<input name="name" value="${esc(c?.name||'')}" maxlength="50" required></label><div class="modal-actions"><button type="button" class="btn light" data-action="close">Отмена</button><button class="btn">Сохранить</button></div></form>`)}
function confirmAction(message,action,id){openEditor(`<h2>Подтвердите действие</h2><p>${esc(message)}</p><div class="modal-actions"><button class="btn light" data-action="close">Назад</button><button class="btn" data-action="${action}" data-id="${esc(id)}">Подтвердить</button></div>`)}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.hash.startsWith('#/')&&!e.ctrlKey&&!e.metaKey){e.preventDefault();go(a.hash.slice(1));return}const b=e.target.closest('[data-action]');if(!b)return;const id=b.dataset.id;switch(b.dataset.action){case'add':add(id);break;case'select':selected=id;render();break;case'category':category=id;render();break;case'next':case'prev':{const list=db.dishes.filter(d=>d.available&&(category==='all'||d.category===category));if(!list.length)return;selected=list[(list.findIndex(d=>d.id===selected)+(b.dataset.action==='next'?1:-1)+list.length)%list.length].id;render();break}case'plus':if(cart[id]<99)cart[id]++;saveCart();render();break;case'minus':if(--cart[id]<=0)delete cart[id];saveCart();render();break;case'remove':delete cart[id];saveCart();render();break;case'filter':filter=id;render();break;case'status':{db=read(KEY,seed);const o=db.orders.find(o=>o.id===id);const allowed={new:'cooking',cooking:'ready',ready:'served'};if(o&&allowed[o.status]===b.dataset.status){o.status=b.dataset.status;save();render();toast('Статус обновлён')}break}case'cancel':confirmAction('Отменить этот заказ?','confirm-cancel',id);break;case'confirm-cancel':{db=read(KEY,seed);const o=db.orders.find(o=>o.id===id);if(o&&['new','cooking'].includes(o.status)){o.status='cancelled';save()}editor.close();render();break}case'edit-dish':editDish(id);break;case'edit-category':editCategory(id);break;case'delete-dish':confirmAction('Удалить блюдо из меню? В истории заказов оно останется.','confirm-delete-dish',id);break;case'confirm-delete-dish':db.dishes=db.dishes.filter(d=>d.id!==id);delete cart[id];saveCart();save();editor.close();render();break;case'delete-category':if(db.dishes.some(d=>d.category===id)){toast('Сначала перенесите или удалите блюда этой категории');return}confirmAction('Удалить пустую категорию?','confirm-delete-category',id);break;case'confirm-delete-category':db.categories=db.categories.filter(c=>c.id!==id);save();editor.close();render();break;case'close':editor.close();break;case'drawer':{const el=document.createElement('aside');el.className='drawer';el.innerHTML='<button class="icon-btn" data-action="close-drawer" aria-label="Закрыть меню">×</button><a href="#/">Меню ресторана</a><a href="#/orders">Мои заказы</a><a href="#/cart">Корзина</a><a href="#/kitchen">Кухня</a><a href="#/admin">Управление</a>';app.append(el);break}case'close-drawer':b.closest('.drawer').remove();break}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.change==='table'){table=Number(t.value);setSession('meridian-table',table);render()}if(t.dataset.change==='available'){dish(t.dataset.id).available=t.checked;save();toast('Меню обновлено')}});
async function imageData(file){if(file.size>3*1024*1024)throw new Error('Фото должно быть меньше 3 МБ');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Выберите JPG, PNG или WebP');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas');const scale=Math.min(1,800/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/webp',.82)}
document.addEventListener('submit',async e=>{const f=e.target;if(!['checkout','dish-form','category-form'].includes(f.id))return;e.preventDefault();const fd=new FormData(f);if(f.id==='checkout'){db=read(KEY,seed);const items=cartItems();if(!items.length)return;if(items.some(({d})=>!d.available)){toast('Уберите недоступные блюда из корзины');return}table=Number(fd.get('table'));setSession('meridian-table',table);const o={id:uid(),number:String(db.orders.length+1).padStart(3,'0'),table,status:'new',created:Date.now(),note:String(fd.get('note')).trim(),items:items.map(({d,qty})=>({id:d.id,name:d.name,price:d.price,qty})),total:subtotal()};db.orders.push(o);if(!save()){db.orders.pop();return}cart={};saveCart();go('/order/'+o.id);return}if(f.id==='category-form'){const name=String(fd.get('name')).trim();if(!name)return;if(db.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.id!==f.dataset.id)){toast('Такая категория уже есть');return}const c=db.categories.find(c=>c.id===f.dataset.id);if(c)c.name=name;else db.categories.push({id:uid(),name});if(save()){editor.close();render();toast('Категория сохранена')}return}if(f.id==='dish-form'){const submit=f.querySelector('[type=submit]');submit.disabled=true;try{const old=dish(f.dataset.id);let image=old?.image||'assets/salmon.png';const photo=fd.get('photo');if(photo?.size)image=await imageData(photo);const d={id:old?.id||uid(),name:String(fd.get('name')).trim(),line1:String(fd.get('line1')).trim(),line2:String(fd.get('line2')).trim(),category:String(fd.get('category')),price:Number(fd.get('price')),weight:Number(fd.get('weight')),time:Number(fd.get('time')),description:String(fd.get('description')).trim(),ingredients:String(fd.get('ingredients')).trim(),allergens:String(fd.get('allergens')).trim(),available:fd.has('available'),image};if(!d.name||!d.description||!(d.price>0))throw new Error('Заполните название, описание и цену');const before=clone(db);if(old)db.dishes=db.dishes.map(x=>x.id===d.id?d:x);else db.dishes.push(d);if(!save()){db=before;return}editor.close();render();toast('Блюдо сохранено')}catch(err){toast(err.message)}finally{submit.disabled=false}}});
window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===KEY){db=read(KEY,seed);if(!editor.open)render()}if(e.key===CART){cart=read(CART,{});if(!editor.open)render()}});
if(!getLocal(KEY))save();render();if(storageUnavailable)toast('Сохранение отключено браузером: данные доступны до закрытия страницы');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_restaurant_menu',description:'Read currently available dishes and their prices.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({dishes:db.dishes.filter(d=>d.available).map(({id,name,price,category})=>({id,name,price,category}))})})).catch(()=>{});Promise.resolve(document.modelContext.registerTool({name:'add_dish_to_cart',description:'Add an available dish to the cart. Does not submit an order.',inputSchema:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:1,maximum:99}},required:['id','quantity'],additionalProperties:false},execute:({id,quantity})=>add(id,quantity)})).catch(()=>{})}catch{}}
